spring:
#  application:
#    name: api-service
  datasource:
    url: jdbc:mysql://192.168.0.111/rspsdb?useUnicode=true&characterEncoding=utf-8
    username: rspsadmin
    password: rsps!@#Test
    driver-class-name: com.mysql.jdbc.Driver
#    druid:
#      db-type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8080
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.baomidou.ant.entity
